### ISSUE TITLE
Error: Nest can't resolve dependencies of the InquirerService (?, DiscoveryService). Please make sure that the argument Symbol(Inquirer) at index [0] is available in the CommandModule context.

### ISSUE THREAD

**Issue by Sotatek-TyPham** [jmcdo29/nest-commander#582]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Import InquirerService to constructor of Command class.

### Minimum reproduction code

```
export class BasicCommand extends CommandRunner {
  constructor(private readonly inquirerService: InquirerService) {
    super()
  }
...
}
```
```
import { Module } from '@nestjs/common';
import { CreateAdminCommand } from "../commands/create-admin.command";
import { CreateAdminQuestions } from "../commands/questions/create-admin.questions";
import { InquirerService } from "nest-commander";

@Module({
  imports: [],
  providers: [
    CreateAdminCommand,
    CreateAdminQuestions,
    InquirerService,
  ],
  exports: [],
})
export class CommandModule {
}
```

### Expected behavior

Not get error:
```
[Nest] 5184  - 09/13/2022, 8:57:24 AM   ERROR [ExceptionHandler] Nest can't resolve dependencies of the InquirerService (?, DiscoveryService). Please make sure that the argument Symbol(Inquirer) at index [0] is available in the CommandModule context.

Potential solutions:
- If Symbol(Inquirer) is a provider, is it part of the current CommandModule?
- If Symbol(Inquirer) is exported from a separate @Module, is that module imported within CommandModule?
  @Module({
    imports: [ /* the Module containing Symbol(Inquirer) */ ]
  })

Error: Nest can't resolve dependencies of the InquirerService (?, DiscoveryService). Please make sure that the argument Symbol(Inquirer) at index [0] is available in the CommandModule context.

Potential solutions:
- If Symbol(Inquirer) is a provider, is it part of the current CommandModule?
- If Symbol(Inquirer) is exported from a separate @Module, is that module imported within CommandModule?
  @Module({
    imports: [ /* the Module containing Symbol(Inquirer) */ ]
  })

    at Injector.lookupComponentInParentModules (/work/node_modules/@nestjs/core/injector/injector.js:202:19)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at Injector.resolveComponentInstance (/work/node_modules/@nestjs/core/injector/injector.js:157:33)
    at resolveParam (/work/node_modules/@nestjs/core/injector/injector.js:108:38)
    at async Promise.all (index 0)
    at Injector.resolveConstructorParams (/work/node_modules/@nestjs/core/injector/injector.js:123:27)
    at Injector.loadInstance (/work/node_modules/@nestjs/core/injector/injector.js:52:9)
    at Injector.loadProvider (/work/node_modules/@nestjs/core/injector/injector.js:74:9)
    at async Promise.all (index 5)
    at InstanceLoader.createInstancesOfProviders (/work/node_modules/@nestjs/core/injector/instance-loader.js:44:9)
```

### Package

- [X] <code>nest-commander</code>
- [ ] <code>nest-commander-schematics</code>
- [ ] <code>nest-commander-testing</code>

### Package version

3.1.0

### Node.js version

14.16.1

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

### Other

`@types/inquirer": "^8.2.3"`

**Comment by jmcdo29** [comment]
Don't add `InquirierService` to the `providers`. It'll be added by the `CommandRunnerModule` when you run the code

**Comment by jmcdo29** [comment]
No. There's a root module that contains all of the commander specific providers globally that gets added by the `CommandFactory`

**Comment by Sotatek-TyPham** [comment]
@jmcdo29 But I got an error:
```
Nest can't resolve dependencies of the CreateAdminCommand (?, LoginRepository). Please make sure that the argument InquirerService at index [0] is available in the CommandModule context.

Potential solutions:
- If InquirerService is a provider, is it part of the current CommandModule?
- If InquirerService is exported from a separate @Module, is that module imported within CommandModule?
  @Module({
    imports: [ /* the Module containing InquirerService */ ]
  })

Error: Nest can't resolve dependencies of the CreateAdminCommand (?, LoginRepository). Please make sure that the argument InquirerService at index [0] is available in the CommandModule context.

Potential solutions:
- If InquirerService is a provider, is it part of the current CommandModule?
- If InquirerService is exported from a separate @Module, is that module imported within CommandModule?
  @Module({
    imports: [ /* the Module containing InquirerService */ ]
  })

    at Injector.lookupComponentInParentModules (/work/node_modules/@nestjs/core/injector/injector.js:202:19)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at Injector.resolveComponentInstance (/work/node_modules/@nestjs/core/injector/injector.js:157:33)
    at resolveParam (/work/node_modules/@nestjs/core/injector/injector.js:108:38)
    at async Promise.all (index 0)
    at Injector.resolveConstructorParams (/work/node_modules/@nestjs/core/injector/injector.js:123:27)
    at Injector.loadInstance (/work/node_modules/@nestjs/core/injector/injector.js:52:9)
    at Injector.loadProvider (/work/node_modules/@nestjs/core/injector/injector.js:74:9)
    at async Promise.all (index 3)
    at InstanceLoader.createInstancesOfProviders (/work/node_modules/@nestjs/core/injector/instance-loader.js:44:9)
```
Note that I do not run CommandFactory in main.ts, I create a cli.js for that.

**Comment by jmcdo29** [comment]
Do you have a [minimum reproduction repository](https://minimum-reproduction.wtf)? You're probably creating a `CommandRunner` provider inside of your `NestFactory` application that is a `NestApplication` instance and not a `NestApplicationContext` instance created via the `CommandFactory`

**Comment by Sotatek-TyPham** [comment]
@jmcdo29 This is my repository https://github.com/typv/nest-commanderr

**Comment by jmcdo29** [comment]
Why does your `AppModule` import the `CommandModule`

**Comment by Sotatek-TyPham** [comment]
@jmcdo29 Oh, Sorry, my mistake. Maybe I misunderstood this part of the document. Thanks for your support.
`You may have noticed in the [Inquirer](https://nest-commander.jaymcdoniel.dev/docs/features/inquirer/) section a quick mention of adding the question set class to the providers. In fact, both command classes and question set classes are nothing more than specialized providers! Due to this, we can simply add these classes to a module's metadata and make sure that module is in the root module the CommandFactory uses.`

**Comment by jmcdo29** [comment]
Questions as in the question set class, not the inquirer service itself

**Comment by julestruong** [comment]
Hi there, sorry to dig up this thread, but i'm having the same error.
I have a `main.ts` which runs the `listen` thing.
And I have a `cron.ts` which will run commands.

Both bootstrap are based on the same AppModule (because i want to be able to reuse some code in both ways, fastify and commands)

When i run the `cron`, everything works.
But the `main` having this error : 
```
[Nest] 120  - 12/13/2022, 11:28:24 PM   ERROR [ExceptionHandler] Nest can't resolve dependencies of the CreateSpaceComand (?). Please make sure that the argument InquirerService at index [0] is available in the AppModule context.
```

I can copy the main.ts : 
```
import { HttpStatus, ValidationPipe } from '@nestjs/common';
import { NestFactory } from '@nestjs/core';
import {
  FastifyAdapter,
  NestFastifyApplication,
} from '@nestjs/platform-fastify';
import { UserInputError } from 'apollo-server-errors';
import { useContainer, ValidationError } from 'class-validator';
import fastify from 'fastify';
import { Logger } from 'nestjs-pino';

import { AppModule } from './app.module';
import { VersionInterceptor } from './core/interceptor/version.interceptor';
import { transport } from './core/logger/pino-options';
import { CommandFactory } from 'nest-commander';

import requestIdHelper from './core/logger/request-id.helper';

async function bootstrap() {
  const fastifyInstance = fastify({
    genReqId: requestIdHelper,
    logger: {
      transport,
    },
    disableRequestLogging: true,
  });

  const app = await NestFactory.create<NestFastifyApplication>(
    AppModule,
    new FastifyAdapter(fastifyInstance),
    {
      bufferLogs: true,
    },
  );

  app.useLogger(app.get(Logger));

  app.useGlobalInterceptors(new VersionInterceptor());
  // https://github.com/nestjs/nest/issues/528
  useContainer(app.select(AppModule), {
    fallbackOnErrors: true,
  });

  await app.listen(3000, '0.0.0.0');
}

bootstrap();
```

I believe there is something to do with what you said @jmcdo29  
```
You're probably creating a CommandRunner provider inside of your NestFactory application that is a NestApplication instance and not a NestApplicationContext instance created via the CommandFactory
```

But my `Command`s file should be imported inside AppModule right ? so when is InquirerService is injected ?

**Comment by Sotatek-TyPham** [comment]
@julestruong The command may be run standalone, you can create a CommandModule and a ts file as the main.ts (eg: cli.ts). Then you can import CommandModule into cli.ts and run your command with syntax: node dist/cli your_command_name.

**Comment by Sotatek-TyPham** [comment]
@julestruong 
*My cli.ts:
```
#!/usr/bin/env node
import { CommandFactory } from "nest-commander";
import { CommandModule } from './commands/command.module';

async function bootstrap() {
  await CommandFactory.run(CommandModule, ['warn', 'error']);
}
bootstrap();
```
* My CommandModule
```
@Module({
  providers: [
    CreateAdminCommand,
    CreateAdminQuestions,
  ],
  exports: [],
})
export class CommandModule {
}
```
* Inject InquirerService
```
export class CreateAdminCommand extends CommandRunner {
  constructor(
    private readonly inquirer: InquirerService,
  ) {
    super()
  }
```

**Comment by julestruong** [comment]
Yeah. I understood that , but I needed appmodule to be imported in my commandmodule . And also some module exporter by appmodule. 

Thx

**Comment by ab192130** [comment]
I have the same issue. I have no idea how to reuse services and imports that used in AppModule.
In command side everything works. But starting main.ts throws `Please make sure that the argument InquirerService at index [0] is a vailable in the MetadataModule context.` error

**Comment by jmcdo29** [comment]
@ab192130 Please open a new issue with a [minimum reproduction](https://minimum-reproduction.wtf) or create a new discussion topic instead of posting on a solved closed issue

**Comment by ruscon** [comment]
Solution:
Need to use `@Inject(InquirerService)`
```ts
constructor(@Inject(InquirerService) private readonly inquirer: InquirerService) {
  //
}
```

**Comment by Samuel-Brito19** [comment]
@ab192130 did you find a way to do this?

**Comment by SunnyMan617** [comment]
Import CommandModule instead of manually providing InquirerService.


import { Module } from '@nestjs/common';
import { CommandModule } from 'nest-commander'; 
import { CreateAdminCommand } from "./commands/create-admin.command";

@Module({
  imports: [CommandModule], Add this line
  providers: [
    CreateAdminCommand,
    {/* Remove InquirerService from providers */ }
  ],
})
export class CommandModule {}

**Comment by ab192130** [comment]
> [@ab192130](https://github.com/ab192130) did you find a way to do this?

Unfortunately :(
